<?xml version="1.0" encoding="UTF-8"?>
<IGCMarkupDocument xmlns="http://www.opentext.com" majorversion="2" minorversion="13" revision="0">
   <CDLInfo v1="5" v2="5" v3="0" v4="223">
      <DriverInfo v1="2" v2="5" v3="38" v4="52">Pdf2DL</DriverInfo>
      <DriverFormatVersion>2</DriverFormatVersion>
   </CDLInfo>
   <PageList>
      <Page index="0" left="4295.5" bottom="13459" right="14100.1" top="22650" DriverFormatVersion="2" pagename="">
         <AuthorList>
            <Author name="PDFTron">
               <Polygon id="7" creationtime="1549048538" time="1549048546" guid="E0610251D74C4546A26234764ED6BDE6" linewidth="0.3" linestyle="solid" color="255|0|0" drawstyle="hollow" hyperlink="" comment="">
                  <PointList pointcount="5">
                     <Point>
                        <x>5726.12</x>
                        <y>20741.5</y>
                     </Point>
                     <Point>
                        <x>5219.97</x>
                        <y>22098.2</y>
                     </Point>
                     <Point>
                        <x>6246.04</x>
                        <y>21884.7</y>
                     </Point>
                     <Point>
                        <x>6735.25</x>
                        <y>19524</y>
                     </Point>
                     <Point>
                        <x>7867.8</x>
                        <y>21474.9</y>
                     </Point>
                  </PointList>
               </Polygon>
               <NonEditPolygon id="8" creationtime="1549048549" time="1549048551" guid="4EC3098E3DE0CC4ABF585D21994518F8" linewidth="0.3" linestyle="solid" color="255|0|0" drawstyle="hollow" hyperlink="" comment="">
                  <PointList pointcount="32">
                     <Point>
                        <x>11487.1</x>
                        <y>19712.3</y>
                     </Point>
                     <Point>
                        <x>11478.3</x>
                        <y>19634</y>
                     </Point>
                     <Point>
                        <x>11452.3</x>
                        <y>19559.6</y>
                     </Point>
                     <Point>
                        <x>11410.3</x>
                        <y>19492.9</y>
                     </Point>
                     <Point>
                        <x>11354.6</x>
                        <y>19437.1</y>
                     </Point>
                     <Point>
                        <x>11287.9</x>
                        <y>19395.2</y>
                     </Point>
                     <Point>
                        <x>11213.5</x>
                        <y>19369.2</y>
                     </Point>
                     <Point>
                        <x>11135.1</x>
                        <y>19360.4</y>
                     </Point>
                     <Point>
                        <x>9456.88</x>
                        <y>19360.4</y>
                     </Point>
                     <Point>
                        <x>9378.56</x>
                        <y>19369.2</y>
                     </Point>
                     <Point>
                        <x>9304.16</x>
                        <y>19395.2</y>
                     </Point>
                     <Point>
                        <x>9237.42</x>
                        <y>19437.1</y>
                     </Point>
                     <Point>
                        <x>9181.69</x>
                        <y>19492.9</y>
                     </Point>
                     <Point>
                        <x>9139.75</x>
                        <y>19559.6</y>
                     </Point>
                     <Point>
                        <x>9113.72</x>
                        <y>19634</y>
                     </Point>
                     <Point>
                        <x>9104.9</x>
                        <y>19712.3</y>
                     </Point>
                     <Point>
                        <x>9104.9</x>
                        <y>21120.3</y>
                     </Point>
                     <Point>
                        <x>9113.72</x>
                        <y>21198.6</y>
                     </Point>
                     <Point>
                        <x>9139.75</x>
                        <y>21273</y>
                     </Point>
                     <Point>
                        <x>9181.69</x>
                        <y>21339.7</y>
                     </Point>
                     <Point>
                        <x>9237.42</x>
                        <y>21395.5</y>
                     </Point>
                     <Point>
                        <x>9304.16</x>
                        <y>21437.4</y>
                     </Point>
                     <Point>
                        <x>9378.56</x>
                        <y>21463.4</y>
                     </Point>
                     <Point>
                        <x>9456.88</x>
                        <y>21472.3</y>
                     </Point>
                     <Point>
                        <x>11135.1</x>
                        <y>21472.3</y>
                     </Point>
                     <Point>
                        <x>11213.5</x>
                        <y>21463.4</y>
                     </Point>
                     <Point>
                        <x>11287.9</x>
                        <y>21437.4</y>
                     </Point>
                     <Point>
                        <x>11354.6</x>
                        <y>21395.5</y>
                     </Point>
                     <Point>
                        <x>11410.3</x>
                        <y>21339.7</y>
                     </Point>
                     <Point>
                        <x>11452.3</x>
                        <y>21273</y>
                     </Point>
                     <Point>
                        <x>11478.3</x>
                        <y>21198.6</y>
                     </Point>
                     <Point>
                        <x>11487.1</x>
                        <y>21120.3</y>
                     </Point>
                  </PointList>
               </NonEditPolygon>
               <NonEditPolygon id="10" creationtime="1549048568" time="1549048570" guid="9BF5544FFC740C418965638F7F20CF33" linewidth="0.3" linestyle="solid" color="255|0|0" drawstyle="hollow" hyperlink="" comment="">
                  <PointList pointcount="4">
                     <Point>
                        <x>5556.89</x>
                        <y>18836.6</y>
                     </Point>
                     <Point>
                        <x>9882.08</x>
                        <y>18836.6</y>
                     </Point>
                     <Point>
                        <x>9882.08</x>
                        <y>15812.4</y>
                     </Point>
                     <Point>
                        <x>5556.89</x>
                        <y>15812.4</y>
                     </Point>
                  </PointList>
               </NonEditPolygon>
            </Author>
         </AuthorList>
      </Page>
   </PageList>
</IGCMarkupDocument>